name: Release container app to Docker Hub

on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string
      tag_version:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -al
          cd ${{ inputs.working_dir }}
          echo "Current working directory: $(pwd)"
          ls -al
      - uses: docker/setup-buildx-action@v3
      - uses: azure/login@v2
        with:
          client-id: 8c198c22-9a34-4857-8e78-b78fbe6fbbec
          tenant-id: 4983917f-34f2-4ad8-90a2-d8dad7c99f18
          subscription-id: f3d1de09-72d9-4869-90b2-3daf03eecda2
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          ls -al
          cd ${{ inputs.working_dir }}
          echo "Current working directory: $(pwd)"
          ls -al
      - uses: falti/dotenv-action@v1.0.4
        with:
          path: ${{ inputs.working_dir }}/env
      - run: |
          make docker-buildx IMAGE_TAG=${{ inputs.tag_version }}
      - uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ env.RELEASE_RESOURCE_GROUP }}
          containerAppName: ${{ env.RELEASE_CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.RELEASE_CONTAINER_APP_IMAGE }}:${{ inputs.tag_version }}
          targetPort: ${{ env.RELEASE_CONTAINER_APP_PORT }}